### ISSUE TITLE
Not able to get friend list

### ISSUE THREAD

**Issue by rohitjindal1184** [lucascorrea/SCFacebook#11]
Hi,
 When i try to run your demo. i am unable to get the friend list. it returns empty array. When i debug the code, i get that Facebook SDK method returning the No of friends but not the friend list.

Thanks

**Comment by lucascorrea** [comment]
Hello @rohitjindal1184  , the new facebook api is returned only friends using your app.

https://developers.facebook.com/docs/graph-api/reference/v2.1/user/friends

This will only return any friends who have used (via Facebook Login) the app making the request.

**Comment by rohitjindal1184** [comment]
HI,

There is any way to get friends.

**Comment by lucascorrea** [comment]
You could use the 1.0 version, but ....

The current, latest version of the Graph API is v2.2. Apps calling v1.0 have Until April 30, 2015 to upgrade to v2.0 or later.

https://developers.facebook.com/docs/graph-api/reference/v1.0/user/friends?locale=pt_BR
