### ISSUE TITLE
facebook sdk update

### ISSUE THREAD

**Issue by syrakozz** [lucascorrea/SCFacebook#12]
could you plz update the project to make him work with the latest facebook sdk

**Comment by foffux** [comment]
Any news about it?

**Comment by syrakozz** [comment]
@lucascorrea

**Comment by lucascorrea** [comment]
I am working to update the version of FacebookSDK 4.0 that came out day 25 of March. I think that until this week I sent a update.

**Comment by lucascorrea** [comment]
Changed many things 

https://developers.facebook.com/docs/ios/change-log-4.x

**Comment by syrakozz** [comment]
great thank you



—

**Comment by foffux** [comment]
Thank you.
We will wait for this big improvement.

**Comment by jaumevn** [comment]
@lucascorrea, Any news about the update?

**Comment by shivanraptor** [comment]
Facebook iOS SDK is changing rapidly recently. Now jumped to v4.4.0. Hope this library will support the latest version soon.

**Comment by foffux** [comment]
Wasting your time
If you want Facebook, use its own SDK. 
I have been waiting for long time, this library is completely stopped 
Now I have switched. The best choice 
Hope this advice can help you 

Inviato da iPhone

**Comment by lucascorrea** [comment]
Guys, sorry for the delay, I finished the frame with facebook sdk 4.6, comitei in another branch (facebook4.0), will test before moving up to master if they want to help test would be great.
