### ISSUE TITLE
Failed to keep the Facebook login session after re-open the app

### ISSUE THREAD

**Issue by alanfeng99** [lucascorrea/SCFacebook#14]
Hi,

I have experience a problem to retain the facebook login session once I re-open the app, I will need to perform login again.

Haven't found the problem yet, please share your insights if possible.

Thanks.

**Comment by lucascorrea** [comment]
Guys, sorry for the delay, I finished the frame with facebook sdk 4.6, comitei in another branch (facebook4.0), will test before moving up to master if they want to help test would be great.
