### ISSUE TITLE
I am not getting Friend List.

### ISSUE THREAD

**Issue by googler2013** [lucascorrea/SCFacebook#17]
Hi, This is great library for Facebook data fetching,

I am getting one issue in that, i have run this code, 

I am successfully login and getting profile data also, but when i am call get friend not getting friend list, can you please help me for the same.

I am debug the app then i have seen at one point in response i am getting friends count but not getting friend data like below.

{
    data =     (
    );
    summary =     {
        "total_count" = 309;
    };
}

Please guide me for the same.

**Comment by aryansbtloe** [comment]
Hi 
Its because facebook is not sending that data . 
you will need to setup your app to get permission for fetching friendlist on facebook.

**Comment by lucascorrea** [comment]
This will only return any friends who have used (via Facebook Login) the app making the request.  If a friend of the person declines the user_friends permission, that friend will not show up in the friend list for this person.

     https://developers.facebook.com/docs/graph-api/reference/v2.4/user/friends/
